### ISSUE TITLE
Understanding inheritance in base.py

### ISSUE THREAD

**Issue by connorjward** [OP2/PyOP2#625]
I'm not sure that inheritance it is being applied correctly in `base.py`.

 To use `Set` as a motivating example, I don't understand why `GlobalSet`, `ExtrudedSet`, `Subset` and `MixedSet` all inherit from `Set` since they overload most, if not all, of the methods defined by it. As far as I can tell the inheritance serves no goal other than to permit `isinstance(obj, Set)` and `issubclass(obj, Set)` checks.

To me it seems as though `Set` is being used simultaneously as an interface *and* as an implementation that interface. I think it would make more sense to create an `AbstractSet` class to define the interface instead that `Set`, `GlobalSet`, `ExtrudedSet`, `Subset` and `MixedSet` could all implement. The same logic would apply to `Map`, `DataSet` and `Dat`.

**Comment by wence-** [comment]
I think that's a reasonable characterisation. Note that there's an opportunity here to clean things up as well. For example `Subset`, `ExtrudedSet` can't be turned into a `DataSet`.

**Comment by wence-** [comment]
> I'd definitely be interested in cleaning things up although I'm not sure what the best design here would be. Some ideas that I've had are:
> 
> * Is it correct that mixed objects inherit from their non-mixed counterpart (e.g. `class MixedSet(Set):`)? To me a container of objects is very different to the objects themselves.

I think probably not. I think the mixed objects are "bags of things".

However, things we should think about to permit possible future developments are if "bags of things" can be nested. It would be useful to maintain structure in a mixed set (or mixed dataset) for saying "this is composed of two mixed things", rather than flattening.

> * If all we ever do is convert a `MixedSet` to a `MixedDataSet` do we even need it to exist?

Maybe not.

> * We could enforce that a `DataSet` can only be formed from a `Set` using inheritance (i.e. `class DataSet(Set):`).

I think the relationship between `DataSet` and `Set` is a `has-a` relationship, not an `is-a` relationship. Notice that to construct a `DataSet` one already needs a `Set` lying around. Whereas inheritance says that a `DataSet` implements all the `Set` interfaces (plus some more). But this isn't the case since a dataset may not be iterated over (I think?).

**Comment by connorjward** [comment]
Great, thanks! I'll look to implement some of this and the rest I think can be revisited later on once I've tackled more of my long list of PyOP2 improvements.
